In [2]:
import pandas as pd
train_df = pd.read_csv("house/train.csv", encoding="utf-8")
test_df = pd.read_csv("house/test.csv", encoding="utf-8")

FileNotFoundError: [Errno 2] No such file or directory: 'house/train.csv'

In [ ]:
total_df = pd.concat([train_df, test_df], axis=0)
total_df

In [10]:
# data是你處理的對象
data = total_df.drop(["SalePrice"], axis=1)
y_train = train_df["SalePrice"]

In [26]:
# 補缺: 中位數
med = data.median().drop(["MSSubClass"])
data = data.fillna(med)

In [28]:
# One-Hot
data = pd.get_dummies(data)
data = pd.get_dummies(data, columns=["MSSubClass"])
data = data.drop(["Id"], axis=1)
data

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190
0,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,...,0,0,0,0,0,0,0,0,0,0
1,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,...,0,0,0,0,0,0,0,0,0,0
2,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,...,0,0,0,0,0,0,0,0,0,0
3,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,540.0,...,1,0,0,0,0,0,0,0,0,0
4,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,490.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,546.0,...,0,0,0,0,0,0,0,1,0,0
1455,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,294.0,...,0,0,0,0,0,0,0,1,0,0
1456,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1457,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,...,0,0,0,1,0,0,0,0,0,0
1458,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
s = data.isna().sum()
s[s > 0]

Series([], dtype: int64)

In [32]:
# 先補完 最後才用到, 分開x_train, x_test
train_df.shape
# loc: 列標籤, iloc: 0, 1...
# iloc -> ["第一筆", "第二筆"....]
x_train = data.iloc[:train_df.shape[0]]
x_test = data.iloc[train_df.shape[0]:]
x_test

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190
0,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,...,0,0,0,0,0,0,0,0,0,0
1,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,...,0,0,0,0,0,0,0,0,0,0
2,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,...,0,0,0,0,0,0,0,0,0,0
3,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,324.0,...,0,0,0,0,0,0,0,0,0,0
4,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,1017.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,546.0,...,0,0,0,0,0,0,0,1,0,0
1455,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,294.0,...,0,0,0,0,0,0,0,1,0,0
1456,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1457,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,...,0,0,0,1,0,0,0,0,0,0
1458,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# 找參數
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score
reg = RandomForestRegressor()
params = {
    "n_estimators":range(20, 150, 10),
    "max_depth":range(5, 20)
}
cv = GridSearchCV(reg, params, 
                  scoring="r2", 
                  n_jobs=4, 
                  cv=10)
cv.fit(x_train, y_train)
print(cv.best_params_)
print(cv.best_score_)

In [37]:
reg = RandomForestRegressor(n_estimators=75, max_depth=8)
reg.fit(x_train, y_train)
pre = reg.predict(x_test)
test_id = test_df["Id"]
result = pd.DataFrame({
    "Id":test_id,
    "SalePrice":pre
})
result.to_csv("house_rf.csv", 
              encoding="utf-8",
              index=False)
result

        Id      SalePrice
0     1461  126738.295379
1     1462  149339.029114
2     1463  174543.635668
3     1464  179893.268023
4     1465  199869.094061
...    ...            ...
1454  2915   89925.189050
1455  2916   89428.959821
1456  2917  152338.517766
1457  2918  115884.748273
1458  2919  225624.496674

[1459 rows x 2 columns]